name: Azure pipeline

on:
  push:
    branches:
    - main

jobs:

  tf-run:
    name: Terraform on Azure
    runs-on: ubuntu-latest
    permissions:
      contents: read
 
    steps:

    - name: Step 01 - Terraform Setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.3

    - name: Step 03 - CheckOut GitHub Repo
      uses: actions/checkout@v4

    - name: Step 04 - Authenticate with Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Step 05 - Terraform Init
      run : terraform -chdir=./terraform init -input=false

    - name: Step 06 - Terraform Validate
      run : terraform -chdir=./terraform validate

    - name: Step 07 - Terraform Plan
      run : terraform -chdir=./terraform plan -input=false -out tfplan

    - name: Step 08 - Terraform Apply
      run : terraform -chdir=./terraform apply -auto-approve -input=false tfplan

    - name: Step 09 - Terraform Show
      run : terraform -chdir=./terraform show